# Site Information
site_name: Rokucraft Wiki
site_author: Henry#0009
site_url:
site_description:
repo_name: Rokucraft Wiki
repo_url: https://github.com/Henry055/RokucraftWiki/

# Plugins
plugins:
  - search
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: 'ğŸ”—'
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - abbr
  - pymdownx.snippets
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

# Social links
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://www.rokucraft.com
      name: Rokucraft's Website
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7WNFu3v
      name: Rokucraft's Discord
    - icon: fontawesome/solid/shopping-cart
      link: https://rokucraft.craftingstore.net
      name: Rokucraft's Store
    - icon: fontawesome/solid/map-marker-alt
      link: http://map.rokucraft.com:8123
      name: Rokucraft's Map
    - icon: fontawesome/brands/github
      link: https://github.com/Rokucraft
      name: Rokucraft's Github
    - icon: fontawesome/solid/globe-americas
      link: https://www.planetminecraft.com/member/rokucraft/
      name: Planet Minecraft
# Currently unused socials
    #- icon: fontawesome/brands/twitter
      #link: https://twitter.com/avatarrokucraft
      #name: Rokucraft's Twitter
    #- icon: fontawesome/brands/facebook
      #link: https://www.facebook.com/avatarrokucraft
      #name: Rokucraft's Facebook Page

# Theme customisation
theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    - scheme: slate
      primary: 
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    #- navigation.expand
  font:
    text: Nunito
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github

# Page Tree
nav:
  - Home: index.md
  - Nations:
    - ğŸŒŠ Water Tribes:
      - Overview: Nations/Water/WaterTribe.md
      - Societal Ranks: Nations/Water/SocietalRanks.md
      - Clans:
        - Clan System: Nations/Water/ClanSystem.md
        - Arenqii: Nations/Water/Arenqii.md
        - Angniku: Nations/Water/Angniku.md
        - Koalkoaq: Nations/Water/Koalkoaq.md
        - Heagga: Nations/Water/Heagga.md
        - Yutu: Nations/Water/Yutu.md
    - ğŸ”ï¸ Earth Kingdom:
      - Overview: Nations/Earth/EarthKingdom.md
      - Societal Ranks: Nations/Earth/SocietalRanks.md
      - Legal Systems:
        - Laws: Nations/Earth/Laws.md
        - Mayor System: Nations/Earth/MayorSystem.md
        - Court System: Nations/Earth/CourtSystem.md
    - ğŸ”¥ Fire Nation:
      - Overview: Nations/Fire/FireNation.md
      - Societal Ranks: Nations/Fire/SocietalRanks.md
      - Legal Systems:
        - Laws: Nations/Fire/Laws.md
        - Royal Cabinet: Nations/Fire/RoyalCabinet.md
        - Govenor System: Nations/Fire/GovenorSystem.md
        - Court System: Nations/Fire/CourtSystem.md
      - Military: Nations/Fire/Military.md
    - ğŸ’¨ Air Collective:
      - Overview: Nations/Air/AirCollective.md
      - Societal Ranks: Nations/Air/SocietalRanks.md
      - Air Council: Nations/Air/Council.md
  - Lore:
    - ğŸŸ¡ Artifacts: Lore/artifacts.md
    - ğŸŸ¢ Diseases: Lore/diseases.md
    - ğŸŸ¢ Fauna: Lore/fauna.md
    - ğŸŸ¢ Flora: Lore/flora.md
    - ğŸŸ¢ Food: Lore/food.md
    - ğŸ”´ Historical Figures: Lore/historicalfigures.md
    - ğŸŸ¡ Holidays: Lore/holidays.md
    - ğŸŸ¢ Red Lotus: Lore/redlotus.md
    - ğŸŸ¡ğŸ”´ Religion: Lore/religion.md
    - ğŸŸ¢ğŸŸ¡ Show Characters: Lore/showcharacters.md
    - ğŸŸ¡ğŸ”´ Spirits: Lore/spirits.md
    - ğŸŸ¡ğŸŸ¢ Zodiac: Lore/zodiac.md
  - Roleplay:
    - How To Begin: Roleplay/HowToBegin.md
    - Important Information:
      - Roleplay Guide: Roleplay/RoleplayGuide.md
      - Roleplay Rules: Roleplay/RoleplayRules.md
    - Character Information:
      - Character Creation (?): Roleplay/CharacterGeneration.md
      - Character Introductions: Roleplay/CharacterIntroductions.md
      - Character Applications: Roleplay/CharacterApplications.md
    - Bending Information:
      - Mastery: Roleplay/Mastery.md
      - Sub-Elements: Roleplay/SubElements.md
  - Gameplay:
    - ğŸ’µ Money:
       - Auctioning: Gameplay/Auctioning.md
       - Bug Catching: Gameplay/BugCatching.md
       - Mining: Gameplay/Mining.md
       - Mobs: Gameplay/Mobs.md
       - Quests: Gameplay/Quests.md
       - Tea Brewing: Gameplay/TeaBrewing.md
    - ğŸ® Other:
       - Art: Gameplay/Art.md
       - Bending: Gameplay/Bending.md
       - Cards: Gameplay/Cards.md
       - Chat System (PLACEHOLDER): Gameplay/Chat.md
       - Housing: Gameplay/Housing.md
       - Pets (PLACEHOLDER): Gameplay/Pets.md
  - Server Related:
       - Resource Pack: ServerRelated/ResourcePack.md
       - Rules: ServerRelated/Rules.md
       - Staff: ServerRelated/Staff.md
